### ISSUE TITLE
Fresh template install fails to build

### ISSUE THREAD

**Issue by rjdellecese** [netlify/remix-template#126]
**Describe the bug**
A fresh template install fails to build.

**To Reproduce**
1. Run `npx create-remix@latest --template netlify/remix-template` with Remix `2.0.1`
2. Select `Netlify Functions` (rather than `Netlify Edge Functions`) option when prompted
3. `cd` into the newly-created app directory
4. Run `npx netlify dev`
5. Observe failure

**Expected behavior**
The app builds successfully.

**Details**
```
❯ npx netlify dev
◈ Netlify Dev ◈
◈ Ignored general context env var: LANG (defined in process)
◈ Ignored general context env var: LC_ALL (defined in process)
◈ Setting up local development server
◈ Starting Netlify Dev with custom config

> predev
> rimraf ./public/_redirects


> dev
> remix dev


 💿  remix dev

[warn] The following Remix future flags are now obsolete and can be removed from your remix.config.js file:
- v2_routeConvention

[info] building...
[info] built (478ms)
(node:94531) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
/Users/rjdellecese/code/my-remix-app/build/index.js:12
import { RemixServer } from "@remix-run/react";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1176:20)
    at Module._compile (node:internal/modules/cjs/loader:1218:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Function.Module._load (node:internal/modules/cjs/loader:958:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:169:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)
```

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version: Sonoma 14.0

**Comment by rjdellecese** [comment]
I'm seeing the same error when trying to upgrade a project from Remix v1 to v2, which is why I came here to test a fresh install.

**Comment by miquelarranz** [comment]
I have the exact same issue. Fresh installation with Remix v2, I just followed the steps to deploy it in Netlify but the local environment fails with the same error.

**Comment by rjdellecese** [comment]
I resolved this in my own project by changing `remix.config.js` to `remix.config.mjs`and setting `serverModuleFormat: "cjs"` in the Remix config file. Credit to https://discord.com/channels/770287896669978684/770287896669978687/1157530151811293247.

**Comment by dmvakh** [comment]
the same issue. Fresh install, Remix v2, the local environment fails with the same error.

Node: v18.18.2
OS: MacOS
Version: Sonoma 14.0
