### ISSUE TITLE
POST requests on dev server gives 404

### ISSUE THREAD

**Issue by hejmartin** [netlify/remix-template#136]
**Describe the bug**
POST requests against the Netlify dev server responds with a 404 error with `Function not found...`

**To Reproduce**
1. Run `npx create-remix@latest --template netlify/remix-template`
2. Select `Netlify Functions` when prompted by installer
3. Create a new route `./app/routes/edit.tsx` with a `<Form method="POST">` and an `action` function (see example below)
4. Start server using `netlify dev`
5. Open `localhost:8888/edit` in browser
6. Post form

```tsx
// app/routes/edit.tsx
import { ActionFunctionArgs } from "@remix-run/node";
import { Form } from "@remix-run/react";

export default function Edit() {
    return (
        <Form method="POST">
            <label>
                Title
                <input />
            </label>
            <button type="submit">Save</button>
        </Form>
    )
}

export async function action({ request }: ActionFunctionArgs) {
    return {
        message: "This is a message from the server",
    }
}
```

**Expected behavior**
The page on port `8888` should not crash, it should behave the same as when opening `localhost:3000`, i.e. the Remix dev server, where the POST request works fine. Also, PUT requests seem to work fine on both ports.

I expect to be able to run the netlify dev server locally, as I need to run certain rewrites and redirects specified in `netlify.toml`.

**Screenshots**
On port 3000, the POST works:
<img width="850" alt="image" src="https://github.com/netlify/remix-template/assets/1826675/1864ac45-8b15-44ff-9440-11bb3b3be764">

On port 8888, the POST does not work:
<img width="850" alt="image" src="https://github.com/netlify/remix-template/assets/1826675/8393385a-f07b-4e16-a85d-703efb21bf50">

**Desktop:**
 - OS: Mac OS 14.1.2
 - Browser: Firefox
 - Netlify CLI: netlify-cli/17.15.7 darwin-arm64 node-v20.11.0

**Comment by ascorbic** [comment]
Fixed in latest version
