### ISSUE TITLE
I tried deploying the Remix Netlify template as it is and it failed.

### ISSUE THREAD

**Issue by mbsyaswanth** [netlify/remix-template#142]
**Describe the bug**

**To Reproduce**
1. Create a remix app using netlify template by running `npx create-remix@latest --template netlify/remix-template`
2. run `npm run start` or
3. Try to deploy using instructions in the readme.

**Expected behavior**
Able to deploy the remix netlify template to netlify functions without any errors.

**Screenshots**
![image](https://github.com/netlify/remix-template/assets/22156014/74e98086-716a-423f-932d-659e3ac26843)
![image](https://github.com/netlify/remix-template/assets/22156014/634bc03a-fedd-4a66-9059-c9ef559def1d)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: all
 - Version: any

**Additional context**
The above should be enough. Please reachout if more information is needed.

**Comment by serhalp** [comment]
Hi @mbsyaswanth, is this issue still occurring? This template is working for me at the moment.
