### ISSUE TITLE
`remix.init` script fails if chosen to run during `create-remix` bootstrapping

### ISSUE THREAD

**Issue by Sophon96** [netlify/remix-template#148]
**Describe the bug**
The remix.init script fails when trying to bootstrap a project using this template with no further error message.

**To Reproduce**
1. Run `pnpm create remix@latest --template netlify/remix-template` or `pnpm dlx create-remix@latest --template netlify/remix-template`
2. Complete all the default remix dialog options, choosing to install dependencies
3. Choose to run remix.init script
4. Script will error with no further information.

The script does run properly if one chooses to *not* run it during the create-remix dialog, and runs it after remix has bootstrapped the project (i.e. `pnpm exec remix init`).

**Expected behavior**
The script should run without issue when choosing to run it in the create-remix dialog.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 11

**Comment by pieh** [comment]
This now should be fixed. Thanks for reporting it!

**Comment by Sophon96** [comment]
Awesome, confirmed that it works on my machines!
