### ISSUE TITLE
Remix 2 becoming React Router 7 soon.  Pre-release version is not working with with netlify

### ISSUE THREAD

**Issue by stalexxx** [netlify/remix-template#157]
Please, support RR7 as successor or Remix 2

**Comment by serhalp** [comment]
Hi @stalexxx. We will be supporting React Router 7 when it is stable, but since it's still unstable we haven't begun work on it yet.

**Comment by sierkje** [comment]
it is stable now :)

**Comment by serhalp** [comment]
There's a working Netlify template here: https://github.com/remix-run/react-router-templates/tree/main/netlify.

We'll release a simple Vite plugin to make this more seamless as soon as we can, but in the meantime that template should be a good starting point.

Let us know if you have any questions or issues.
