### ISSUE TITLE
No dev server on port 3000, 8888 serves build only 

### ISSUE THREAD

**Issue by juanpprieto** [netlify/remix-template#92]
**Describe the bug**
I'm trying the Remix/edge template but for the life of me I can't get a regular `dev` workflow going. The README indicates that a dev server will be available at `http://localhost:3000` but `netlify dev` fires up a server at `8888`.

`8888` returns a `404` unless I run `npm run build` which means that `npm run dev` is acting more as a `npm start` (serving) command rather than dev.

Am I missing something?. Everything works as expected in the regular netlify functions template.

**To Reproduce**
1. `npx create-remix@latest --template netlify/remix-edge-template` 
2. `npm run dev`

**Expected behavior**
I'd expect a working dev server with/without hot reloading. e.g Make changes reload see changes.

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser chrome
 - Version latest

**Comment by nickytonline** [comment]
@juanpprieto, thanks for catching this. I'll fix this shortly. Until the fix is up, you can change your remix.config.js to this.

```diff
const { config } = require("@netlify/remix-edge-adapter");
+ const baseConfig =
+  process.env.NETLIFY || process.env.NETLIFY_LOCAL ? config : {};
+
/**
 * @type {import('@remix-run/dev').AppConfig}
 */
module.exports = {
-  ...config,
+ ...baseConfig, 
  // This works out of the box with the Netlify adapter, but you can
  // add your own custom config here if you want to.
  //
  // See https://remix.run/docs/en/v1/file-conventions/remix-config
};
```

**Comment by nickytonline** [comment]
Thanks for the issue @juanpprieto. Looking into this.
